name: CI Test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      solution-path: ./src/HassClient.sln
    strategy:
      matrix:
        channel:
          - stable

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.solution-path}}
      
    - name: 👷 Setup Home Assistant
      id: homeassistant
      uses: ludeeus/setup-homeassistant@main
      with:
          tag: ${{ matrix.channel }}

    - name: ✅ Verify API Access
      run: | 
        curl -sSL -f -X GET \
          -H "Authorization: Bearer ${{ steps.homeassistant.outputs.token }}" \
          -H "Content-Type: application/json" \
          ${{ steps.homeassistant.outputs.url }}/api/states
          
    - name: Test
      run: dotnet test --no-restore --verbosity normal ${{env.solution-path}} --configuration Release
      env:
          TestsInstanceBaseUrl: ${{ steps.homeassistant.outputs.url }}
          TestsAccessTokenVar: ${{ steps.homeassistant.outputs.token }}

    - name: 📜 Get logs
      run: docker logs ${{ steps.homeassistant.outputs.containername }}
